package model

type DraftMerchants struct {
	No            		string   `gorm:"column:No"`
	AgentNo       		string   `gorm:"column:agent_no"`
	SalesNo       		string   `gorm:"column:sales_no"`
	Registration  		string   `gorm:"column:registration"`
	Name          		string   `gorm:"column:name"`
	ShortName     		string   `gorm:"column:short_name"`
	WxMerchantId  		string   `gorm:"column:wx_merchant_id"`
	TypeName      		string   `gorm:"column:type"`
	Logo          		string   `gorm:"column:logo"`
	ServicePhone  		string   `gorm:"column:service_phone"`
	CountryCode   		string   `gorm:"column:country_code"`
	ClientInfo    		string   `gorm:"column:client_info"`
	ClientRemark  		string   `gorm:"column:client_remark"`
	ClientUrl     		string   `gorm:"column:client_url"`
	ChargeRate   	    string   `gorm:"column:charge_rate"`
	MinBalance    		string   `gorm:"column:min_balance"`
	AllowCurrency 		string   `gorm:"column:allow_currency"`
	RegisterCountry     string   `gorm:"column:register_country"`
	BeginDate     		string   `gorm:"column:begin_date"`
	EndDate       		string   `gorm:"column:end_date"`
	Files         		string   `gorm:"column:files"`
	Pacts         		string   `gorm:"column:pacts"`
	Remark        		string   `gorm:"column:remark"`
	ContactName   		string   `gorm:"column:contact_name"`
	ContactEmail  		string   `gorm:"column:contact_email"`
	ContactPhone  		string   `gorm:"column:contact_phone"`
	BeginTime     		string   `gorm:"column:begin_time"`
	EndTime       		string   `gorm:"column:end_time"`
	AvgTransactionAmt   string   `gorm:"column:avg_transaction_amt"`
	InviteNo      		string   `gorm:"column:invite_no"`
	IsOffline     		string   `gorm:"column:is_offline"`
	MerchantType 		string   `gorm:"column:merchant_type"`
	MccCode       		string   `gorm:"column:mcc_code"`
	AlipayMerchantNo    string   `gorm:"column:alipay_merchant_no"`
	AliChargeRate       string   `gorm:"column:ali_charge_rate"`
	IndustryType 	    string   `gorm:"column:industry_type"`
	SignSub             string   `gorm:"column:sign_sub"`
	PayChannel   		string   `gorm:"column:pay_channel"`
	WxAllowCurrency 	string   `gorm:"column:wx_allow_currency"`
	AliAllowCurrency 	string   `gorm:"column:ali_allow_currency"`
	AliflChargeRate 	string   `gorm:"column:alifl_charge_rate"`
	DbaName             string   `gorm:"column:dba_name"`
	StoreAddress        string   `gorm:"column:store_address"`
	AliflAllowCurrency  string   `gorm:"column:alifl_allow_currency"`
	WxflAllowCurrency   string   `gorm:"column:wxfl_allow_currency"`
	WxflChargeRate      string   `gorm:"column:wxfl_charge_rate"`
	Agent               Agents   `gorm:"ForeignKey:No;AssociationForeignKey:AgentNo"`
}
